// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdmuspajldbjzgrfdfgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkbXVzcGFqbGRianpncmZkZmdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQyNTQ4NDAsImV4cCI6MjA3OTgzMDg0MH0.vqdPM3c1z_DKs0I8cgb7_tDgVnSgzvfwllln8fEvr3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
